using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;

namespace onYOURway.Models {

	[Table("Realms", Schema = "oyw")]
	public partial class Realm {

		/// <summary>
		/// Unique id
		/// </summary>
		[Key]
		public Int32 Id { get; set; }

		/// <summary>
		/// Pattern to recognize Realm to Url
		/// </summary>
		public String UrlPattern { get; set; }

		/// <summary>
		/// Native name e.g. used as title in realm description
		/// </summary>
		public String Name { get; set; }

		/// <summary>
		/// Native description
		/// </summary>
		public String Description { get; set; }

		/// <summary>
		/// Root tag of the taxonomy used by this realm thus selecting the available taxonomy
		/// </summary>
		public Int32 TaxonomyId { get; set; }

		/// <summary>
		/// Optional geographical focus of the realm. Null means worldwide.
		/// </summary>
		[JsonConverter(typeof(DbGeographyConverter))]
		public DbGeography Boundary { get; set; }

		#region navigation properties

		/// <summary>
		/// Navigation property 
		/// </summary>
		/// <remarks>Joins and foreign keys are generated by this</remarks>
		public virtual ICollection<RealmLocalized> Localizations { get; set; }
		
		#endregion navigation properties

	}///Realm


	[Table("RealmsLocalized", Schema="oyw")]
	public partial class RealmLocalized {

		/// <summary>
		/// Key of realm to be localized
		/// </summary>
		[Key, Column(Order = 0)]
		public Int32 RealmId { get; set; }

		/// <summary>
		/// Locale e.g. "de-DE" or language e.g. "de" of localization
		/// </summary>
		[Key, Column(Order = 1), MinLength(2), MaxLength(5)]
		public string Locale { get; set; }

		/// <summary>
		/// Localized name
		/// </summary>
		public String Name { get; set; }

		/// <summary>
		/// Localized description
		/// </summary>
		public String Description { get; set; }

		#region navigation properties

		[ForeignKey("RealmId")]
		public virtual Realm Realm { get; set; }

		#endregion navigation properties

	} //RealmLocalized

}
