using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
	
namespace onYOURway.Models {

	[Table("oyw.Realms")]
	public partial class Realm {

		/// <summary>
		/// Unique key (used to associate entries to realms and e.g. as part of the URL)
		/// </summary>
		[Key, MaxLength(40)]
		public String Key { get; set; }

		/// <summary>
		/// International name e.g. used as title in realm description
		/// </summary>
		public String Name { get; set; }

		/// <summary>
		/// International description
		/// </summary>
		public String Description { get; set; }

		/// <summary>
		/// Id or Key of the RootElement of the taxonomy used by this realm thus selecting the available taxonomy
		/// </summary>
		public String TaxonomyKey { get; set; }

		/// <summary>
		/// Optional geographical focus of the realm. Null means worldwide.
		/// </summary>
		public DbGeography Boundary { get; set; }

		/// <summary>
		/// Navigation property 
		/// </summary>
		/// <remarks>Joins and foreign keys are generated by this</remarks>
		[InverseProperty("RealmKey")] //define Key in RealmsLocalized to be the ForeignKey in RealmLocalized pointing to this
		public virtual ICollection<RealmLocalized> Localizations { get; set; }

		/// <summary>
		/// URIs, URLs this realm is responsible for
		/// </summary>
		public virtual ICollection<RealmUri> Uris { get; set; }
	
	}///Realm

	public partial class RealmUri {

		/// <summary>
		/// Key of realm
		/// </summary>
		[Key, Column(Order = 0), MaxLength(40)]
		public String RealmKey { get; set; }

		[Key, Column(Order = 1), Index(IsUnique = true), MaxLength(200)]
		public Uri Uri { get; set; }

		/// <summary>
		/// Navigation property
		/// </summary>
		[ForeignKey("RealmKey")]
		public virtual Realm Realm { get; set; }

	}

	public partial class RealmLocalized {

		/// <summary>
		/// Key of realm to be localized
		/// </summary>
		[Key, Column(Order = 0), MaxLength(40)]
		public String RealmKey { get; set; }

		/// <summary>
		/// Locale e.g. "de-DE" or language e.g. "de" of localization
		/// </summary>
		[Key, Column(Order = 1), MinLength(2), MaxLength(5)]
		public string Locale { get; set; }

		/// <summary>
		/// Localized name
		/// </summary>
		public String Name { get; set; }

		/// <summary>
		/// Localized description
		/// </summary>
		public String Description { get; set; }

	} //RealmLocalized

}
