//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public string NAME { get; set; }
        public string ISO3 { get; set; }
        public string ISO2 { get; set; }
        public string FIPS { get; set; }
        public string COUNTRY1 { get; set; }
        public string ENGLISH { get; set; }
        public string FRENCH { get; set; }
        public string SPANISH { get; set; }
        public string LOCAL { get; set; }
        public string FAO { get; set; }
        public string WAS_ISO { get; set; }
        public string SOVEREIGN { get; set; }
        public string CONTINENT { get; set; }
        public string UNREG1 { get; set; }
        public string UNREG2 { get; set; }
        public Nullable<int> EU { get; set; }
        public Nullable<float> SQKM { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
    }
}
