//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionView
    {
        public long RegionId { get; set; }
        public int ViewId { get; set; }
        public string Name { get; set; }
        public int ListOrder { get; set; }
        public System.Data.Entity.Spatial.DbGeography Boundary { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
