//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Aliases = new HashSet<RegionAlias>();
            this.Views = new HashSet<RegionView>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public Nullable<long> OsmRelationId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public System.Data.Entity.Spatial.DbGeography Boundary { get; set; }
    
        public virtual ICollection<RegionAlias> Aliases { get; set; }
        public virtual ICollection<RegionView> Views { get; set; }
    }
}
