//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public long UserId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string Item { get; set; }
        public bool Checked { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
