//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HasTag
    {
        public long LocationId { get; set; }
        public int TagId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
