//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.ForeignIds = new HashSet<LocationForeignId>();
            this.ProductSuggestions = new HashSet<ProductSuggestion>();
            this.Links = new HashSet<LocationLink>();
            this.Aliases = new HashSet<LocationAlias>();
            this.Tags = new HashSet<HasTag>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Lang { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string Phone { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        [JsonConverter(typeof(DbGeographyConverter))]
        public System.Data.Entity.Spatial.DbGeography Position { get; set; }
        public string Icon { get; set; }
        public string OpeningHours { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<LocationForeignId> ForeignIds { get; set; }
        public virtual ICollection<ProductSuggestion> ProductSuggestions { get; set; }
        public virtual ICollection<LocationLink> Links { get; set; }
        public virtual ICollection<LocationAlias> Aliases { get; set; }
        public virtual ICollection<HasTag> Tags { get; set; }
    }
}
