//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationOpen
    {
        public LocationOpen()
        {
            this.Hours = new HashSet<LocationOpenHour>();
        }
    
        public long LocationId { get; set; }
        public int OpenId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<LocationOpenHour> Hours { get; set; }
        public virtual Location Location { get; set; }
    }
}
