//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.LocationForeignIds = new HashSet<LocationForeignId>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<LocationForeignId> LocationForeignIds { get; set; }
    }
}
