//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportLine
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Ref { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Mode { get; set; }
        public string Network { get; set; }
        public string Operator { get; set; }
        public string Color { get; set; }
        public System.Data.Entity.Spatial.DbGeography Way { get; set; }
    }
}
