//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onYOURway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportStop
    {
        public long Id { get; set; }
        public string LineIds { get; set; }
        public string Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography Position { get; set; }
    }
}
